"""identidade, inquilino e trilha

Revision ID: 9b2e8f63be3c
Revises: 
Create Date: 2026-09-06 01:13:06.022361
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b2e8f63be3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilino',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_falho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_falho_email_quando', 'login_falho', ['email', 'quando'], unique=False)
    op.create_table('token_servico',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('escopo', sa.String(length=200), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquilino_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('troca_senha_obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_usuario_email')
    )
    op.create_index('ix_usuario_inquilino', 'usuario', ['inquilino_id'], unique=False)
    op.create_table('identidade',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('provedor', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('segredo_hash', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provedor', 'subject', name='uq_identidade_provedor_subject')
    )
    op.create_index('ix_identidade_usuario', 'identidade', ['usuario_id'], unique=False)
    op.create_table('sessao_dono',
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('inquilino_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_sessao_dono_inquilino', 'sessao_dono', ['inquilino_id'], unique=False)
    op.create_table('solicitacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquilino_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('decidida_por', sa.String(length=36), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decidida_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solicitacao_estado', 'solicitacao', ['estado'], unique=False)
    op.create_table('trilha',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inquilino_id', sa.String(length=36), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('doc_id', sa.String(length=64), nullable=True),
    sa.Column('acao', sa.String(length=32), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('quando', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trilha_doc', 'trilha', ['doc_id'], unique=False)
    op.create_index('ix_trilha_inquilino_quando', 'trilha', ['inquilino_id', 'quando'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trilha_inquilino_quando', table_name='trilha')
    op.drop_index('ix_trilha_doc', table_name='trilha')
    op.drop_table('trilha')
    op.drop_index('ix_solicitacao_estado', table_name='solicitacao')
    op.drop_table('solicitacao')
    op.drop_index('ix_sessao_dono_inquilino', table_name='sessao_dono')
    op.drop_table('sessao_dono')
    op.drop_index('ix_identidade_usuario', table_name='identidade')
    op.drop_table('identidade')
    op.drop_index('ix_usuario_inquilino', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('token_servico')
    op.drop_index('ix_login_falho_email_quando', table_name='login_falho')
    op.drop_table('login_falho')
    op.drop_table('inquilino')
    # ### end Alembic commands ###
